version: '3.8'

services:

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks: 
      - net1
      
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - menu-service
      - order-service
      - payment-service
      - inventory-service
      - customer-service
    networks: 
      - net1
     
  customer-service:
    build:
        context: ./customer-services
        dockerfile: Dockerfile
    container_name: customer-service
    ports:
      - "3005:3005"
    networks: 
      - net1

  inventory-service:
    build:
        context: ./inventory-services
        dockerfile: Dockerfile
    container_name: inventory-service
    ports:
      - "3004:3004"
    networks: 
      - net1

  menu-service:
    build:
        context: ./menu-services
        dockerfile: Dockerfile
    container_name: menu-services
    ports:
      - "3001:3001"
    networks: 
      - net1

  order-service:
    build:
        context: ./order-services
        dockerfile: Dockerfile
    container_name: order-service
    depends_on:
      - menu-service
      - customer-service
      - inventory-service
    ports:
      - "3002:3002"
    networks: 
      - net1

  payment-service:
    build:
        context: ./payment-services
        dockerfile: Dockerfile
    container_name: payment-service
    depends_on:
      - order-service
    ports:
      - "3003:3003"
    networks: 
      - net1
networks: 
  net1:
    external: true

