name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
     - name: Checkout repository
     - uses: actions/checkout@v4

     - name: Set up Docker Buildx
     - uses: docker/setup-buildx-action@v3

     - name: Login to DockerHub
     - uses: docker/login-action@v3
       with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

     - name: Build docker image of api-gateway and push it into repo
       uses: docker/build-push-action@v5
       with:
          context: ./api-gateway
          push: true
          tags: affanwajid123/api-gateway
          
     - name: Build docker image of customer-services and push it into repo
       uses: docker/build-push-action@v5
       with:
          context: ./customer-services
          push: true
          tags: affanwajid123/customer-services
          
     - name: Build docker image of inventory-services and push it into repo
       uses: docker/build-push-action@v5
       with:
          context: ./inventory-services
          push: true
          tags: affanwajid123/inventory-services 
          
     - name: Build docker image of menu-services and push it into repo
       uses: docker/build-push-action@v5
       with:
          context: ./menu-services
          push: true
          tags: affanwajid123/menu-services
          
     - name: Build docker image of order-services and push it into repo
       uses: docker/build-push-action@v5
       with:
          context: ./order-services
          push: true
          tags: affanwajid123/order-services
          
     - name: Build docker image of payment-services and push it into repo
       uses: docker/build-push-action@v5
       with:
          context: ./payment-services
          push: true
          tags: affanwajid123/payment-services

